import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import * as serviceWorker from './serviceWorker';

let myToken = sessionStorage.getItem('myToken');
if(!myToken)
    sessionStorage.setItem('myToken', 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6ImQ0YTlhYTM5MDBiZDBjODMxZjNlYTgzNzI5ZWM5NDQxYzMwOTQ4YTIzYzM0MzMxNTEwZGE3MGE5OGFlMGExZTEwZTM2NWYyMmNiMTE2NDNkIn0.eyJhdWQiOiI0IiwianRpIjoiZDRhOWFhMzkwMGJkMGM4MzFmM2VhODM3MjllYzk0NDFjMzA5NDhhMjNjMzQzMzE1MTBkYTcwYTk4YWUwYTFlMTBlMzY1ZjIyY2IxMTY0M2QiLCJpYXQiOjE1NTAzMzkxMDEsIm5iZiI6MTU1MDMzOTEwMSwiZXhwIjoxNTUwNDI1NTAxLCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.dgDn7zslxvmGo1aW8K5FQF0rK8Vr3y953AGMVAKr3pVTFl4d6vF15eBW_xQ_krbqxsny2NENUj9bcyvc9NB9uC56J9i72h4r0OHDI3ubfUb1jbQ3b3q6YB5yFUdkWpLnfPAeXf2xirhBV87xEX_kPEVaydSq2dDsq0tq2KPisi5Ov8O4DTLlWyUVx_dbvHJXHYBBhFnIXmGDnw2WW6DbzJR9TxtoHL7syZ5G3E3b0ZXXE1yPC1UmLmJMnR6Ya3Ei_X0l0Rgm2e-enhjqPWKrgh_KY_bl7NCoyXekLh7q8nTwKSEbUD8KD8fA_yFaI8TTdiyWpgtrs1iIlKkwMbFOlzizn_uzEJ2soGLyHbHeFqhJI7B62ilwooBJiDEcNN4KWqYcwv6wqslmJvfI7G9DEhJSFh85QhxjrlQSKCFeL6zLGWDXUCq8ocrFcJHNFXR_Jv0HlL8YFG2YTZXUKXUhGRgpSEP5_XGzmf2Kvi74d9l-TlMAi_BHv-HFmz9O7wuQ2T2YMKbtVFu52dZDhgG_A0Sh2M2qoNr02DBDZBWzRJrw-Xx4T_udm_bSDIk_NoJuwO-OZESBX92MH8FZxa7RwlTNvPwYcTWhZa9vSTVpL49tokwTwMqQUJ3jl10odR8prG6FyJdaUQ7Yi7q8miMhxdCol_QT9kuBT8xY9HlbIlQ');

ReactDOM.render(<App />, document.getElementById('root'));

// If you want your app to work offline and load faster, you can change
// unregister() to register() below. Note this comes with some pitfalls.
// Learn more about service workers: http://bit.ly/CRA-PWA
serviceWorker.unregister();
